CREATE OR REPLACE TRIGGER TRG_INC_UPD_TBJENTEPI_BJ
BEFORE INSERT OR UPDATE ON AD_TBJENTEPI FOR EACH ROW
DECLARE

BEGIN

    IF UPDATING THEN

        :NEW.CODUSULAN := STP_GET_CODUSULOGADO;
        :NEW.DTINCLUSAO := SYSDATE;

    END IF;

END;
